mod commands;
mod events;
mod services;
mod state;

use events::{
    DoneEvent, ErrorEvent, StatusEvent, TextDeltaEvent, ThinkingDeltaEvent, ToolCallDeltaEvent,
    ToolResultEvent, ToolStartEvent, UsageEvent,
};
use state::AppState;
use tauri_specta::{collect_commands, collect_events, Builder};

fn make_builder() -> Builder<tauri::Wry> {
    Builder::<tauri::Wry>::new()
        .commands(collect_commands![
            commands::app::app_info,
            commands::agent::agent_send_message,
            commands::session::session_load,
            // Plan 3.3 F1 — session archive/delete commands consumed by lib/bridge/session.ts
            commands::session::toggle_archive_agent_session,
            commands::session::delete_agent_session,
            // Plan 2b.2.c.3 — file-attachment Tauri commands consumed by InlineImage +
            // screenshot-result via the frontend bridge/files.ts wrapper.
            commands::files::read_attachment,
            commands::files::save_image_as,
            // Plan 3.2 — folder picker for WorkspaceCreateDialog.
            commands::files::open_folder_dialog,
            // Plan 3.2 — workspace CRUD commands consumed by lib/bridge/workspaces.ts
            commands::workspaces::workspace_list,
            commands::workspaces::workspace_create,
            commands::workspaces::workspace_update,
            commands::workspaces::workspace_delete,
            commands::workspaces::workspace_reorder,
            commands::workspaces::workspace_get_active,
            commands::workspaces::workspace_set_active,
        ])
        .events(collect_events![
            TextDeltaEvent,
            ToolCallDeltaEvent,
            UsageEvent,
            DoneEvent,
            ErrorEvent,
            ToolStartEvent,
            ToolResultEvent,
            ThinkingDeltaEvent,
            StatusEvent,
        ])
}

#[cfg_attr(mobile, tauri::mobile_entry_point)]
pub fn run() {
    let builder = make_builder();

    #[cfg(debug_assertions)]
    builder
        .export(
            specta_typescript::Typescript::default().header(
                r#"// AUTOGENERATED by tauri-specta. Do not edit this file manually.
//
// IMPORTANT: do NOT import the `commands` or `events` objects directly from this file.
//   - `commands` bypasses lib/bridge/client.ts error normalization. Use the
//     domain namespaces from @/lib/bridge instead (appBridge, agentBridge, sessionBridge).
//   - `events` uses tauri-specta's auto-derived names (e.g. `done-event`), but the
//     Rust backend emits on `agent:*` names (e.g. `agent:done`). Use the typed
//     `listenAgent(...)` helper in lib/bridge/events.ts instead.
//
// Types-only imports from this file are fine and encouraged.
"#,
            ),
            "../src/lib/bridge/generated.ts",
        )
        .expect("failed to export specta bindings");

    tauri::Builder::default()
        .plugin(tauri_plugin_dialog::init())
        .plugin(tauri_plugin_opener::init())
        .manage(AppState::init())
        .invoke_handler(builder.invoke_handler())
        .setup(move |app| {
            builder.mount_events(app);
            Ok(())
        })
        .run(tauri::generate_context!())
        .expect("error while running tauri application");
}

#[cfg(all(test, debug_assertions))]
mod tests {
    use super::*;

    /// Generates `desktop/src/lib/bridge/generated.ts` from the current command set.
    /// Run with: cargo test -p hermes-desktop export_bindings
    #[test]
    fn export_bindings() {
        make_builder()
            .export(
                specta_typescript::Typescript::default().header(
                    r#"// AUTOGENERATED by tauri-specta. Do not edit this file manually.
//
// IMPORTANT: do NOT import the `commands` or `events` objects directly from this file.
//   - `commands` bypasses lib/bridge/client.ts error normalization. Use the
//     domain namespaces from @/lib/bridge instead (appBridge, agentBridge, sessionBridge).
//   - `events` uses tauri-specta's auto-derived names (e.g. `done-event`), but the
//     Rust backend emits on `agent:*` names (e.g. `agent:done`). Use the typed
//     `listenAgent(...)` helper in lib/bridge/events.ts instead.
//
// Types-only imports from this file are fine and encouraged.
"#,
                ),
                "../src/lib/bridge/generated.ts",
            )
            .expect("failed to export specta bindings");
    }
}
