mod commands;
mod events;
mod services;
mod state;

use state::AppState;
use tauri_specta::{collect_commands, collect_events, Builder};
use events::{
    TextDeltaEvent, ToolCallDeltaEvent, UsageEvent, DoneEvent, ErrorEvent,
    ToolStartEvent, ToolResultEvent, ThinkingDeltaEvent, StatusEvent,
};

fn make_builder() -> Builder<tauri::Wry> {
    Builder::<tauri::Wry>::new()
        .commands(collect_commands![
            commands::app::app_info,
            commands::agent::agent_send_message,
            commands::session::session_load,
        ])
        .events(collect_events![
            TextDeltaEvent,
            ToolCallDeltaEvent,
            UsageEvent,
            DoneEvent,
            ErrorEvent,
            ToolStartEvent,
            ToolResultEvent,
            ThinkingDeltaEvent,
            StatusEvent,
        ])
}

#[cfg_attr(mobile, tauri::mobile_entry_point)]
pub fn run() {
    let builder = make_builder();

    #[cfg(debug_assertions)]
    builder
        .export(
            specta_typescript::Typescript::default()
                .header(r#"// AUTOGENERATED by tauri-specta. Do not edit this file manually.
//
// IMPORTANT: do NOT import the `commands` or `events` objects directly from this file.
//   - `commands` bypasses lib/bridge/client.ts error normalization. Use the
//     domain namespaces from @/lib/bridge instead (appBridge, agentBridge, sessionBridge).
//   - `events` uses tauri-specta's auto-derived names (e.g. `done-event`), but the
//     Rust backend emits on `agent:*` names (e.g. `agent:done`). Use the typed
//     `listenAgent(...)` helper in lib/bridge/events.ts instead.
//
// Types-only imports from this file are fine and encouraged.
"#),
            "../src/lib/bridge/generated.ts",
        )
        .expect("failed to export specta bindings");

    tauri::Builder::default()
        .plugin(tauri_plugin_opener::init())
        .manage(AppState::init())
        .invoke_handler(builder.invoke_handler())
        .setup(move |app| {
            builder.mount_events(app);
            Ok(())
        })
        .run(tauri::generate_context!())
        .expect("error while running tauri application");
}

#[cfg(all(test, debug_assertions))]
mod tests {
    use super::*;

    /// Generates `desktop/src/lib/bridge/generated.ts` from the current command set.
    /// Run with: cargo test -p hermes-desktop export_bindings
    #[test]
    fn export_bindings() {
        make_builder()
            .export(
                specta_typescript::Typescript::default()
                    .header(r#"// AUTOGENERATED by tauri-specta. Do not edit this file manually.
//
// IMPORTANT: do NOT import the `commands` or `events` objects directly from this file.
//   - `commands` bypasses lib/bridge/client.ts error normalization. Use the
//     domain namespaces from @/lib/bridge instead (appBridge, agentBridge, sessionBridge).
//   - `events` uses tauri-specta's auto-derived names (e.g. `done-event`), but the
//     Rust backend emits on `agent:*` names (e.g. `agent:done`). Use the typed
//     `listenAgent(...)` helper in lib/bridge/events.ts instead.
//
// Types-only imports from this file are fine and encouraged.
"#),
                "../src/lib/bridge/generated.ts",
            )
            .expect("failed to export specta bindings");
    }
}
