// AUTOGENERATED by tauri-specta — do not edit manually.
// DO NOT import `commands` directly from this file.
// Consumers must go through `@/lib/bridge` namespace bridges (e.g. `appBridge.appInfo()`).
// Raw `commands.*` calls bypass error normalisation in `lib/bridge/client.ts`.

// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	appInfo: () => __TAURI_INVOKE<AppInfo>("app_info"),
};

/* Types */
/**  Basic application metadata surfaced to the frontend. */
export type AppInfo = {
	name: string,
	version: string,
	platform: string,
};

