// AUTOGENERATED by tauri-specta — do not edit manually.
// DO NOT import `commands` directly from this file.
// Consumers must go through `@/lib/bridge` namespace bridges (e.g. `appBridge.appInfo()`).
// Raw `commands.*` calls bypass error normalisation in `lib/bridge/client.ts`.

// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";
import * as __TAURI_EVENT from "@tauri-apps/api/event";

/** Commands */
export const commands = {
	appInfo: () => __TAURI_INVOKE<AppInfo>("app_info"),
	agentSendMessage: (sessionId: string, text: string) => typedError<string, AgentSendError>(__TAURI_INVOKE("agent_send_message", { sessionId, text })),
	sessionLoad: (sessionId: string) => typedError<SessionMessage_Serialize[], SessionLoadError>(__TAURI_INVOKE("session_load", { sessionId })),
};

/** Events */
export const events = {
	doneEvent: makeEvent<DoneEvent_Deserialize>("done-event"),
	errorEvent: makeEvent<ErrorEvent>("error-event"),
	textDeltaEvent: makeEvent<TextDeltaEvent>("text-delta-event"),
	toolCallDeltaEvent: makeEvent<ToolCallDeltaEvent_Deserialize>("tool-call-delta-event"),
	usageEvent: makeEvent<UsageEvent_Deserialize>("usage-event"),
};

/* Types */
export type AgentSendError = {
	message: string,
};

/**  Basic application metadata surfaced to the frontend. */
export type AppInfo = {
	name: string,
	version: string,
	platform: string,
};

export type DoneEvent = DoneEvent_Serialize | DoneEvent_Deserialize;

export type DoneEvent_Deserialize = {
	session_id: string,
	reason: string | null,
};

export type DoneEvent_Serialize = {
	session_id: string,
	reason?: string | null,
};

export type ErrorEvent = {
	session_id: string,
	message: string,
};

export type SessionLoadError = {
	message: string,
};

/**
 *  Frontend-facing message shape. Mirrors `hermes_core::Message` but only
 *  surfaces the fields the UI cares about for v1.
 */
export type SessionMessage = SessionMessage_Serialize | SessionMessage_Deserialize;

/**
 *  Frontend-facing message shape. Mirrors `hermes_core::Message` but only
 *  surfaces the fields the UI cares about for v1.
 */
export type SessionMessage_Deserialize = {
	role: string,
	content: string | null,
};

/**
 *  Frontend-facing message shape. Mirrors `hermes_core::Message` but only
 *  surfaces the fields the UI cares about for v1.
 */
export type SessionMessage_Serialize = {
	role: string,
	content?: string | null,
};

export type TextDeltaEvent = {
	session_id: string,
	text: string,
};

export type ToolCallDeltaEvent = ToolCallDeltaEvent_Serialize | ToolCallDeltaEvent_Deserialize;

export type ToolCallDeltaEvent_Deserialize = {
	session_id: string,
	index: number,
	function_name: string | null,
	arguments_chunk: string | null,
	call_id: string | null,
};

export type ToolCallDeltaEvent_Serialize = {
	session_id: string,
	index: number,
	function_name?: string | null,
	arguments_chunk?: string | null,
	call_id?: string | null,
};

export type UsageEvent = UsageEvent_Serialize | UsageEvent_Deserialize;

export type UsageEvent_Deserialize = {
	session_id: string,
	/**
	 *  Token counts are capped at u32 for frontend JSON-number safety (u64 exceeds
	 *  JS Number precision; LLM responses comfortably fit in ~4 B tokens).
	 */
	prompt_tokens: number,
	completion_tokens: number,
	total_tokens: number,
	estimated_cost: number | null,
};

export type UsageEvent_Serialize = {
	session_id: string,
	/**
	 *  Token counts are capped at u32 for frontend JSON-number safety (u64 exceeds
	 *  JS Number precision; LLM responses comfortably fit in ~4 B tokens).
	 */
	prompt_tokens: number,
	completion_tokens: number,
	total_tokens: number,
	estimated_cost?: number | null,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

type EventEmit<T> = [T] extends [null] ? () => Promise<void> : (payload: T) => Promise<void>;

function makeEvent<T>(name: string, serialize?: (payload: T) => unknown, deserialize?: (payload: any) => T) {
    const mapEvent = (cb: __TAURI_EVENT.EventCallback<T>) => (event: __TAURI_EVENT.Event<any>) => cb({ ...event, payload: deserialize ? deserialize(event.payload) : event.payload });
    const mapPayload = (payload: T) => serialize ? serialize(payload) : payload;

    const base = {
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.once(name, mapEvent(cb)),
        emit: ((payload: T) => __TAURI_EVENT.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    };

    const fn = (target: import("@tauri-apps/api/webview").Webview | import("@tauri-apps/api/window").Window) => ({
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => target.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => target.once(name, mapEvent(cb)),
        emit: ((payload: T) => target.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    });

    return Object.assign(fn, base);
}

